### ISSUE TITLE
关于代码高亮问题与一些想法

### ISSUE THREAD

**Issue by ghost** [iJinxin/hexo-theme-sky#1]
您好，您的主题非常棒，但代码高亮部分支持的语言太少了，且不支持自动换行。
希望在访问文章内容是网站标题为文章内容标题-网站标题。

以上是个人的一些想法，谢谢~

**Comment by jinxin-max** [comment]
> 您好，您的主题非常棒，但代码高亮部分支持的语言太少了，且不支持自动换行。
> 希望在访问文章内容是网站标题为文章内容标题-网站标题。
> 
> 以上是个人的一些想法，谢谢~

这个项目的初衷是做一个简洁版的博客主题，但这不该是功能支持不友好的理由，正好打算年后出一套新方案，你的建议我会采纳的。thanks。

**Comment by ghost** [comment]
> 
> 
> > 您好，您的主题非常棒，但代码高亮部分支持的语言太少了，且不支持自动换行。
> > 希望在访问文章内容是网站标题为文章内容标题-网站标题。
> > 以上是个人的一些想法，谢谢~
> 
> 这个项目的初衷是做一个简洁版的博客主题，但这不该是功能支持不友好的理由，正好打算年后出一套新方案，你的建议我会采纳的。thanks。

 谢谢，您的解答。期待您的新主题。
